export const REQUEST_UPDATE_DAYS = "REQUEST_UPDATE_DAYS";
export const SUCCESS_UPDATE_DAYS = "SUCCESS_UPDATE_DAYS";
export const ERROR_UPDATE_DAYS = "ERROR_UPDATE_DAYS";
export const REQUEST_ROWS_DATA = "REQUEST_ROWS_DATA"; 
export const SUCCESS_ROWS_DATA = "SUCCESS_ROWS_DATA"; 
export const ERROR_ROWS_DATA = "ERROR_ROWS_DATA"; 
